name: docExtractor
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - cairo=1.14.12
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - cloudpickle=1.3.0
  - cudatoolkit=10.0.130
  - cudnn=7.3.1
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.14.0
  - decorator=4.4.2
  - ffmpeg=4.0.2
  - fontconfig=2.13.1
  - freeglut=3.0.0
  - freetype=2.10.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - gmp=6.1.2
  - gnutls=3.5.19
  - graphite2=1.3.13
  - harfbuzz=1.9.0
  - hdf5=1.10.2
  - icu=58.2
  - imageio=2.8.0
  - intel-openmp=2020.0
  - jasper=2.0.14
  - jpeg=9c
  - kiwisolver=1.2.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libopencv=3.4.2
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4-c=1.8.3
  - matplotlib-base=3.1.3
  - mkl=2020.0
  - ncurses=6.2
  - nettle=3.3
  - networkx=2.4
  - ninja=1.10.0
  - numpy=1.16.3
  - olefile=0.46
  - opencv=3.4.2
  - openh264=1.8.0
  - openssl=1.1.1f
  - pcre=8.44
  - pillow=5.4.1
  - pip=19.0.3
  - pixman=0.34.0
  - pthread-stubs=0.4
  - py-opencv=3.4.2
  - pycparser=2.20
  - pyparsing=2.4.7
  - python=3.6.8
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=1.0.1
  - pywavelets=1.1.1
  - pyyaml=5.1
  - readline=7.0
  - scikit-image=0.16.2
  - scipy=1.4.1
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - toolz=0.10.0
  - torchvision=0.2.2
  - tornado=6.0.4
  - unidecode=1.0.23
  - wheel=0.34.2
  - x264=1!152.20180806
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - arabic-reshaper==2.0.15
    - chardet==3.0.4
    - future==0.18.2
    - idna==2.9
    - pdf2image==1.5.4
    - python-bidi==0.4.2
    - requests==2.23.0
    - urllib3==1.25.8
